version: '3'
services:
  gpd:
    image: robopaas/rosdocked-noetic-gpd:latest
    hostname: gpd
    environment:
    - ROS_HOSTNAME=gpd
    - ROS_MASTER_URI=http://rosdocked:11311
    depends_on:
      - rosdocked
    command: tail -f /dev/null

  rosdocked:
    image: robopaas/rosdocked-noetic-k8s:latest
    hostname: rosdocked
    environment:
      - ROS_HOSTNAME=rosdocked
    volumes:
      - $PWD:/host
    ports:
      - "80:8080"
